# Generated by Django 5.2.3 on 2025-06-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_transaction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="product_names",
            field=models.TextField(blank=True, default=""),
        ),
    ]
